### ISSUE TITLE
[Backend]: Update .env

### ISSUE THREAD

**Issue by niklhut** [PhyExDB/PhyExDB#134]
### Description

As a developer I want to have an up to date .env description in .env.example and no redundant values in nuxt.config.ts

### Acceptance Criteria

Check the environment values in nuxt.config.ts and see if the token secrets are still required now that we use betterAuth. Also document the betterAuthSecret in the .env.example.

**Comment by suiluj482** [comment]
redundant values in nuxt.config.ts are allready gone
