### ISSUE TITLE
[Backend]: User Endpoint

### ISSUE THREAD

**Issue by niklhut** [PhyExDB/PhyExDB#31]
### Description

As a developer I want a user endpoint.

### Acceptance Criteria

There should be an endpoint to get a list of users, get a detail of a user, create a user and update a user.

**Comment by LeviAchenbach** [comment]
should the list of users contain every attribute from the user table or just the names and ids?

**Comment by niklhut** [comment]
I would say for the list it should be id, username, role (but this is not implemented yet, needs #54 first) verified. For the detail, I think we should return the email only when the user themselves requests the detail because of data privacy reasons, otherwise anyone could get out the emails. So depending on the user who requests the detail the email is sent or not. And the password Hash should never be sent to a client
