### ISSUE TITLE
[Backend]: Change user role endpoint

### ISSUE THREAD

**Issue by niklhut** [PhyExDB/PhyExDB#35]
### Description

As a developer I want an api endpoint to change the user role.

### Acceptance Criteria

An endpoint to change the user role should be available. Only an admin should be able to change the role of others. An admin cannot change their own role but the role of another admin. This ensures that there always is at least one admin.

**Comment by suiluj482** [comment]
consider https://www.better-auth.com/docs/plugins/admin

**Comment by niklhut** [comment]
Closing this as it is part of better auth
