### ISSUE TITLE
[Backend]: Experiment Attribute Endpoints

### ISSUE THREAD

**Issue by niklhut** [PhyExDB/PhyExDB#38]
### Description

There should be endpoints for all experiment attributes (see #37).

### Acceptance Criteria

There should be an endpoint to get all attributes, all attributes per value and add a new attribute value to an existing attribute. An attribute and attribute value should also be able to be updated.

**Comment by FinnKeller** [comment]
should there be an endpoint for adding attributes or only for adding adding attribute values ?

**Comment by niklhut** [comment]
I think because attributes are fixed values (they are the things you can filter your search by like Themenbreiche and Versuchart) adding a new attribute is not important since they could not later be integrated into the search. However, adding values seems important because in these categories a new value might come up.

**Comment by FinnKeller** [comment]
in the acceptance criteria it says that there should be an endpoint to get all attributes per value but it should be the other way around. The endpoint should return all values per Attribute or am I misunderstanding something ?
