### ISSUE TITLE
[Backend]: Experiment Model

### ISSUE THREAD

**Issue by niklhut** [PhyExDB/PhyExDB#42]
### Description

As a developer I want an experiment model.

### Acceptance Criteria

There should be a model for experiment. It should have an id, a visible attribute a title and be referenced by ExperimentSections (see #41) and Attributes (see #37). The experiment duration should also be a field of type int (duration in minutes)

**Comment by niklhut** [comment]
Instead of a visible status an additional Enum ExperimentStatus is a better idea, it should have the values draft, submitted, accepted to enable an additional draft state of an experiment. For enums see https://sequelize.org/docs/v7/models/data-types/#enums

**Comment by LeviAchenbach** [comment]
@niklhut, was genau meinst du damit, dass Experiment refferenced werden soll von ExperimentSection und Attributes. Soll es dann in den Modellen von den beiden eine refference auf das ExperimentModel geben?

**Comment by niklhut** [comment]
@LeviAchenbach das kannst du erstmal weg lassen, wir hatten ja abgesprochen, dass wir die References in einem extra issue machen
